services:
  redis:
    image: redis
    container_name: gm_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - D:/Docker/redis_volume:/data
      - D:/Docker/redis_volume/redis-v/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - goodsmall-network

#  redis-insight:
#    image: redis/redisinsight
#    container_name: gm_redisinsight
#    restart: always
#    ports:
#      - 5540:5540
#    volumes:
#      - D:/Docker/redisinsight_volume:/data
#    environment:
#      - REDIS_URL=redis://redis:6379
#    depends_on:
#      - redis
#    networks:
#      - goodsmall-network

  mysql:
    image: mysql
    container_name: gm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: goodsmall
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - D:\Docker\mysql/data:/var/lib/mysql
      - D:\Docker\mysql/config:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - goodsmall-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: gm_zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - goodsmall-network

  kafka:
    image: bitnami/kafka:latest
    container_name: gm_kafka
    ports:
      - "9092:9092"
    environment:
#      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: gm_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://gm_kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      KAFKA_MIN_INSYNC_REPLICAS: 2
    depends_on:
      - zookeeper
    networks:
      - goodsmall-network

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=gm_kafka:9092"
      - "--web.listen-address=0.0.0.0:9308"
    depends_on:
      - kafka
    networks:
      - goodsmall-network


networks:
  goodsmall-network:
    external: true
