application:
  container_name: goodsMall
  restart: on-failure
  build:
    context: ./
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc://mysql:3306/goodsmall?allowPublicKeyRetrieval=true
    SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
    SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  depends_on:
    mysql:
      condition: service_healthy
    redis:
      condition: service_healthy