services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka
      - kafka-exporter
    networks:
      - goodsmall-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - kafka-exporter
      - prometheus
      - influxdb
    networks:
      - goodsmall-network


  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: gm_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=k6
    networks:
      - goodsmall-network
  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
    networks:
      - goodsmall-network


networks:
  goodsmall-network:
    driver: bridge
