services:
  redis:
    image: redis
    container_name: gm_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - D:/Docker/redis_volume:/data
      - D:/Docker/redis_volume/redis-v/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - goodsmall-network

  redis-insight:
    image: redis/redisinsight
    container_name: gm_redisinsight
    restart: always
    ports:
      - 5540:5540
    volumes:
      - D:/Docker/redisinsight_volume:/data
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - goodsmall-network

  mysql:
    image: mysql
    container_name: gm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: goodsmall
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - D:\Docker\mysql/data:/var/lib/mysql
      - D:\Docker\mysql/config:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - goodsmall-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: gm_zookeeper
    ports:
      - "2181:2181"
    networks:
      - goodsmall-network

  kafka:
    image: wurstmeister/kafka
    container_name: gm_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: gm_zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - goodsmall-network


networks:
  goodsmall-network:
    driver: bridge
